// Code generated by "generr"; DO NOT EDIT.
package unienv

import "fmt"

func IsNoDefaultSection(err error) bool {
	if _, ok := err.(noDefaultSection); ok {
		return true
	}
	return false
}

type NoDefaultSection struct {
}

func (e *NoDefaultSection) NoDefaultSection() {
	return
}
func (e *NoDefaultSection) Error() string {
	return fmt.Sprint("noDefaultSection")
}
