// Code generated by "generr"; DO NOT EDIT.
package unienv

import "fmt"

func IsNoEnvName(err error) (bool, string) {
	var envname string
	if e, ok := err.(noEnvName); ok {
		envname = e.NoEnvName()
		return true, envname
	}
	return false, envname
}

type NoEnvName struct {
	Envname string
}

func (e *NoEnvName) NoEnvName() string {
	return e.Envname
}
func (e *NoEnvName) Error() string {
	return fmt.Sprintf("noEnvName Envname: %v", e.Envname)
}
